import {mkdir, readFile, writeFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import {dirname, resolve} from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(packageRoot, "../..");
const generatedRoot = resolve(packageRoot, "src/schema/generated");
const check = process.argv.includes("--check");

const inputs = [
  ["net", resolve(repositoryRoot, "spec/net.schema.json")],
  ["composition", resolve(repositoryRoot, "spec/composition.schema.json")],
];

const documents = Object.fromEntries(
  await Promise.all(
    inputs.map(async ([name, path]) => [name, JSON.parse(await readFile(path, "utf8"))]),
  ),
);

const ajv = new Ajv2020({
  allErrors: true,
  code: {esm: true, lines: true, optimize: true, source: true},
  strict: false,
  strictNumbers: true,
  validateFormats: false,
});
ajv.addSchema(documents.net);
ajv.addSchema(documents.composition);

const validatorSource = standaloneCode(ajv, {
  validateComposition: documents.composition.$id,
  validateNet: documents.net.$id,
}).replace(
  /const (func\d+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/g,
  [
    "function $1(value){",
    "let length = 0;",
    "for(let index = 0; index < value.length; index++){",
    "const code = value.charCodeAt(index);",
    "if(code >= 0xd800 && code <= 0xdbff && index + 1 < value.length){",
    "const next = value.charCodeAt(index + 1);",
    "if((next & 0xfc00) === 0xdc00) index++;",
    "}",
    "length++;",
    "}",
    "return length;",
    "}",
  ].join("\n"),
);

if (/\brequire\s*\(|\b(?:new\s+)?Function\s*\(|\bnode:/.test(validatorSource)) {
  throw new Error("Generated validators contain a browser/CSP-incompatible runtime token.");
}

const header = "// Generated by tools/generate-schemas.mjs. Do not edit.\n";
const validators = `${header}// @ts-nocheck -- Ajv emits standalone JavaScript.\n${validatorSource}`;
const schemas = `${header}import type {ReadonlyJsonObject} from "../types.js";\n\nexport const NET_SCHEMA = ${JSON.stringify(documents.net, null, 2)} as const satisfies ReadonlyJsonObject;\n\nexport const COMPOSITION_SCHEMA = ${JSON.stringify(documents.composition, null, 2)} as const satisfies ReadonlyJsonObject;\n`;

const outputs = [
  [resolve(generatedRoot, "validators.ts"), validators],
  [resolve(generatedRoot, "schemas.ts"), schemas],
];

const drift = [];
if (!check) await mkdir(generatedRoot, {recursive: true});

for (const [path, expected] of outputs) {
  if (check) {
    let actual;
    try {
      actual = await readFile(path, "utf8");
    } catch {
      actual = undefined;
    }
    if (actual !== expected) drift.push(path);
  } else {
    await writeFile(path, expected);
  }
}

if (drift.length > 0) {
  console.error(
    `Generated schema artifacts are stale:\n${drift.map((path) => `- ${path}`).join("\n")}\nRun pnpm run generate:schema.`,
  );
  process.exitCode = 1;
} else {
  console.log(check ? "Generated schema artifacts are current." : "Generated schema artifacts updated.");
}
